### ISSUE TITLE
JS errors on rendered page

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/otcdocstheme#139]
developer console shows permanently big amount of JS errors, which are however not influencing UX

**Comment by tischrei** [comment]
@gtema:
could you run and check if it is the same issue when you compile the demo page (tox -e docs)? If I run this example locally, I don't get the errors at all!

@SebastianGode : Could you check this as well.

**Comment by gtema** [comment]
nope, only visible on deployed pages
<img width="1458" alt="Screenshot 2023-02-03 at 16 38 04" src="https://user-images.githubusercontent.com/16461884/216644229-e7e4d21f-980e-4f05-a53c-9f951d34823f.png">

**Comment by SebastianGode** [comment]
That error message appears in case JQuery is not included correctly.
https://stackoverflow.com/questions/22268881/referenceerror-is-not-defined

Where do we include JQuery? I guess in the deployed pages it gets included in the wrong order after the JavaScript files.

**Comment by tischrei** [comment]
I found several possible reasons, but that not find the final conclusion, let's discuss this in telco mode.

**Comment by tischrei** [comment]
The issue is related to jquery which is needed by Sphinx and is shipped by the build process in line 13.
![](https://i.imgur.com/T1WCI29.png)

Due to issue with the latest version of Sphinx Jquery is completely missing. 
We did not find where the Jquery dependency is mentioned.

The tox run works because it uses an old version (4.5.0).
